### PR TITLE
Add pyqt5 support

### PR DESCRIPTION
**Pull request by sjagoe**
This adds support for PyQt5 to jigna while maintaining support for PyQt4 and PySide.

### CODE REVIEW

**Comment by sjagoe** [comment]
Cancelled earlier builds.

**Comment by sjagoe** [comment]
Once we have public builds of PyQt5 we can enable testing that as well.

**Comment by prabhuramachandran** [comment]
@sjagoe -- LGTM!

**Comment by prabhuramachandran** [comment]
@sjagoe -- what about #95?  Is that no longer needed?

**Comment by prabhuramachandran** [comment]
@itziakos -- could you please review this?  I'd like to merge this, test it and add pyside2 support if possible.

**Review by itziakos — APPROVED** [review]

**Comment by prabhuramachandran** [comment]
Thanks!

**Pull request merged**
