### PR TITLE
Server shutdown

### PR DESCRIPTION
**Pull request by mchilvers**

### CODE REVIEW

**Comment by prabhuramachandran** [comment]
Will you be adding some tests?

**Comment by agrawalprash** [comment]
@prabhuramachandran yes I just added a test. The PR looks good to me now. What do you think?

**Comment by prabhuramachandran** [comment]
Looks good to me.  Should something similar be done for a web client, I am guessing no as in the Qt case the server is started each time the widget is opened but this does not happen with the web server as there is only one started for all web clients.

**Comment by agrawalprash** [comment]
Yes we don't want to shut down the web server if one of the clients went offline.

**Comment by prabhuramachandran** [comment]
So is this RTM?  Should I merge it?

**Comment by agrawalprash** [comment]
Yes, this is RTM.

**Pull request merged**
